rjri/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include('web.urls')),
]

web/urls.py
from django.urls import path

from . import views

app_name = 'web'
urlpatterns = [
    path('', views.index, name='index'),
    path('page/',views.page, name='page'),
    path('page/<str:section>',views.page, name='page'),
    path('upload_csv/',views.upload_csv, name='upload_csv'),
]

web/templates/web/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Dashboard</title>

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css" />

	<link rel="stylesheet" type="text/css" href="{% static "web/style.css" %}" />
	
</head>
<body>

<header class="grid-x" id="intro">

		<div class="intro">
			<figure class="logo">
				<!-- <img src="images/RJRI.png" alt="Real Jobs Rhode Island">-->
				<a href="{% url 'web:upload_csv' %}"><img src="{% static "web/images/RJRI.png" %}" alt="Real Jobs Rhode Island"></a>
			</figure>
			
			<h1>Program Report</h1>
			<p>Real Jobs RI grows business-led partnerships that build workforce solutions to address their unique workforce challenges. Solutions can include:</p>
			<ul>
				<li>Placing new employees into immediate job openings;</li>
				<li>Upskilling current employees to advance skills and/or remain competitive;</li>
				<li>Creating pipelines of talent for the future.</li>
			</ul>
			<p>Real Jobs RI is a win-win because companies get the talent they need to compete globally and grow locally, and Rhode Islanders get opportunities to thrive in a flourishing economy.</p>
		</div>
</header>

<nav>
	<div>
		<ul>
			<li><a href="#starts">Employers</a></li>
			<li><a href="#performance">Performance</a></li>
			<li><a href="#finances">Finances</a></li>
			<li><a href="#demographics">Demographics</a></li>
		</ul>
	</div>
</nav>



<div id="main-content-section">


	<div class="grid-x overview section alt" id="starts">
		<div class="cell small-12">
			<h2>It starts with employers...</h2>

			<div class="grid-x" data-equalizer data-equalize-on="medium">
				<div class="cell medium-4">
					<a href="{% url 'web:page' %}Sector_Partnerships" title="lorem ipsum dolor sit amet.">
						<div class="scorecard big" data-equalizer-watch>
							<img src="{% static "web/images/icons/iconmonstr-building-20.svg" %}" class="icon" alt="ofice building" />
							<strong class="score"><span>{{Sector_Partnerships}}</span></strong> <span class="rjri-button">Sector Partnerships</span>
						</div>
					</a>
				</div>
				<div class="cell medium-4">
					<a href="{% url 'web:page' %}Employers_Served" title="lorem ipsum dolor sit amet.">
						<div class="scorecard big" data-equalizer-watch>
							<img src="{% static "web/images/icons/iconmonstr-building-24.svg" %}" class="icon" alt="shop building" />
							<strong class="score"><span>{{Employers_Served}}</span></strong> <span class="rjri-button">Employers Served</span>
						</div>
					</a>
				</div>
				<div class="cell medium-4">
					<a href="{% url 'web:page' %}Industry_Sectors" title="lorem ipsum dolor sit amet.">
						<div class="scorecard big" data-equalizer-watch>
							<img src="{% static "web/images/icons/iconmonstr-building-26.svg" %}" class="icon" alt="industrial building" />
							<strong class="score"><span>{{Industry_Sectors}}</span></strong> <span class="rjri-button">Industry Sectors</span>
						</div>
					</a>
				</div>
			</div>
		</div>
	</div>
	
	<div class="grid-x overview section alt" id="workforce">
		<div class="cell small-12">
			<h2>...who develop workforce solutions...</h2>

			<div class="grid-x" data-equalizer data-equalize-on="medium">
				<div class="cell medium-4">
					<a href="{% url 'web:page' %}New_Hire_Training_Activities" title="lorem ipsum dolor sit amet.">
						<div class="scorecard big">
							<img src="{% static "web/images/icons/iconmonstr-certificate-9.svg" %}" class="icon" alt="certificate" />
							<strong class="score"><span>{{New_Hire_Training_Activities}}</span></strong> <span class="rjri-button">New Hire Training Activities</span>
						</div>
					</a>
				</div>
				<div class="cell medium-4">
					<a href="{% url 'web:page' %}Incumbent_Worker_Training_Activities" title="lorem ipsum dolor sit amet.">
						<div class="scorecard big">
							<img src="{% static "web/images/icons/iconmonstr-school-7.svg" %}" class="icon" alt="training" />
							<strong class="score"><span>{{Incumbent_Worker_Training_Activities}}</span></strong> <span class="rjri-button">Incumbent Worker Training Programs</span>
						</div>
					</a>
				</div>
				<div class="cell medium-4">
					<a href="{% url 'web:page' %}Pipeline_Development_Activities" title="lorem ipsum dolor sit amet.">
						<div class="scorecard big">
							<img src="{% static "web/images/icons/iconmonstr-certificate-6.svg" %}" class="icon" alt="award" />
							<strong class="score"><span>{{Pipeline_Development_Activities}}</span></strong> <span class="rjri-button">Pipeline Development Activities</span>
						</div>
					</a>
				</div>
			</div>
		</div>
	</div>

	<div class="grid-x overview section alt" id="opportunities">
		<div class="cell small-12">
			<h2>...and connect Rhode Islanders with opportunities</h2>

			
			

			<div class="grid-x" data-equalizer data-equalize-on="medium">
				<div class="cell medium-1"><!-- purely for layout --></div>
				<div class="cell medium-2">
					<a href="{% url 'web:page' %}New_Hires_Placed" title="lorem ipsum dolor sit amet.">
						<div class="scorecard" data-equalizer-watch>
							<img src="{% static "web/images/icons/iconmonstr-chart-21.svg" %}" class="icon" alt="" />
							<strong class="score"><span>{{New_Hires_Placed}}</span></strong> <span class="rjri-button">New Hires Placed</span>
						</div>
					</a>
				</div>
				<div class="cell medium-2">
					<a href="{% url 'web:page' %}Incumbent_Workers_Upskilled" title="lorem ipsum dolor sit amet.">
						<div class="scorecard" data-equalizer-watch>
							<img src="{% static "web/images/icons/iconmonstr-school-17.svg" %}" class="icon" alt="" />
							<strong class="score"><span>{{Incumbent_Workers_Upskilled}}</span></strong> <span class="rjri-button">Incumbent Workers Upskilled</span>
						</div>
					</a>
				</div>
				<div class="cell medium-2">
					<a href="{% url 'web:page' %}College_Internships_Completed" title="lorem ipsum dolor sit amet.">
						<div class="scorecard" data-equalizer-watch>
							<img src="{% static "web/images/icons/iconmonstr-book-16.svg" %}" class="icon" alt="Book" />
							<strong class="score"><span>{{College_Internships_Completed}}</span></strong> <span class="rjri-button">College Internships Completed</span>
						</div>
					</a>
				</div>
				<div class="cell medium-2">
					<a href="{% url 'web:page' %}New_Career_Technial_High_School_Programs" title="lorem ipsum dolor sit amet.">
						<div class="scorecard" data-equalizer-watch>
							<img src="{% static "web/images/icons/iconmonstr-id-card-14.svg" %}" class="icon" alt="" />
							<strong class="score"><span>{{New_Career_Technial_High_School_Programs}}</span></strong> <span class="rjri-button">New Career & Technical High School Programs</span>
						</div>
					</a>
				</div>
				<div class="cell medium-2">
					<a href="{% url 'web:page' %}High_School_Students_Completing_Internships" title="lorem ipsum dolor sit amet.">
						<div class="scorecard" data-equalizer-watch>
							<img src="{% static "web/images/icons/iconmonstr-school-11.svg" %}" class="icon" alt="" />
							<strong class="score"><span>{{High_School_Students_Completing_Internships}}</span></strong> <span class="rjri-button">High School Students Completing Internships</span>
						</div>
					</a>
				</div>
				<div class="cell medium-1"><!-- purely for layout --></div>
			</div>
			
		</div>
	</div>
	
	

	<div class="grid-x performance section" id="performance">
	
		<div class="cell small-12">
			<h2>Data and Performance</h2>


			<div class="grid-x" data-equalizer data-equalize-on="small">
		
				<div class="cell medium-4">
						<div class="scorecard big" data-equalizer-watch>
							<img src="{% static "web/images/icons/iconmonstr-chart-16.svg" %}" class="icon" alt="" />
							<strong class="score"><span>{{Placement_Rate}}</span></strong> <span class="rjri-button">Placement Rate</span>
						</div>
				</div>
				<div class="cell medium-4">
						<div class="scorecard big" data-equalizer-watch>
							<img src="{% static "web/images/icons/iconmonstr-banknote-15.svg" %}" class="icon" alt="" />
							<strong class="score"><span>{{Avreage_Wage_After_Placement}}</span></strong> <span class="rjri-button">Average Wage After Placement</span>
						</div>
				</div>
					
				<div class="cell medium-4">
						<div class="scorecard big">
							<img src="{% static "web/images/icons/iconmonstr-certificate-7.svg" %}" class="icon" alt="" />
							<strong class="score"><span>{{Avreage_Wage_Gain}}</span></strong> <span class="rjri-button">Average Wage Gain of Incumbent Workder Trainees</span>
						</div>
				</div>
			
			</div>
			
		</div>

	</div>
	


	<div class="grid-x finances section alt" id="finances">
	
		<div class="cell small-12">
			<h2>Finances</h2>
	

			<div class="grid-x">
				<div class="cell medium-6">
						<div class="scorecard big">
							<img src="{% static "web/images/icons/iconmonstr-coin-7.svg" %}" class="icon" alt="" />
							<strong class="score"><span>{{Cost_Per_Individual}}</span></strong> <span class="rjri-button">Cost Per Individual</span>
						</div>
				</div>
				<div class="cell medium-6">
						<div class="scorecard big">
							<img src="{% static "web/images/icons/iconmonstr-monitoring-1.svg" %}" class="icon" alt="" />
							<strong class="score"><span>{{Benchmark_Cost}}</span></strong> <span class="rjri-button">Benchmark Cost</span>
						</div>
				</div>
			</div>

		</div>
	
	</div>


	<div class="grid-x demographics section" id="demographics">
		<div class="cell small-12">
			<h2>Demographics</h2>
				<div id="gender"></div>
				<div id="education"></div>
				<div id="ethnicity"></div>
		</div>
	</div>
	<p align="right"><font size="2"><B>Demographic data does not include Skills for Rhode Islands Future or Incumbent Worder trainees.&nbsp; &nbsp; </B></font></p>
</div>


	<footer>
		<div class="data-info"><a href="#performance">Data and Performance</a>, <a href="#overview">Overview</a>, <a href="#finances">Finances</a>, <a href="#demographics">Demographics</a> data as of 10/31/2017.</div>
		<div class="by">
			<a href="https://datasparkri.org"><img src="{% static "web/images/dataspark-logo.png" %}" width="107" height="50" alt="Dataspark"></a>
			<a href="https://www.uri.edu"><img src="{% static "web/images/the-university-or-rhode-island-logo.png" %}"  width="126" height="50" alt="The University of Rhode Island"></a>
		</div>
	</footer>

	<!-- Compressed JavaScript -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/js/foundation.min.js"></script>

	<script src="https://code.highcharts.com/highcharts.js"></script>
	<script src="https://code.highcharts.com/modules/exporting.js"></script>

	<script src="{% static "web/js/script.min.js" %}"></script>
	

	<script>
		$(document).foundation();
	</script>
</body>
</html>

web/templates/web/page.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Dashboard</title>

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css" />

	<link rel="stylesheet" href="{% static 'web/style.css' %}"/>
	
</head>
<body>

<header class="grid-x" id="intro">

		<div class="intro">
			<figure class="logo">
				<!-- <img src="images/RJRI.png" alt="Real Jobs Rhode Island">-->
				<a href="{% url 'web:index' %}"><img src="{% static "web/images/RJRI.png" %}" alt="Real Jobs Rhode Island"></a>
			</figure>
			
			<h1>{{title}}</h1>
			<p><strong>Definition:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed imperdiet erat at enim consectetur, in suscipit dolor ullamcorper. Integer condimentum porta elit eget rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse eget egestas purus. Vestibulum id sollicitudin ante. Duis quis congue leo, venenatis pharetra elit. Praesent et nunc sed sem faucibus semper id at mi. Nullam et consequat diam. Donec porta vehicula mauris quis bibendum. Nulla tincidunt posuere eros, ac molestie lorem.</p>
			
			<p><a href="http://www.dlt.ri.gov/realjobs/pdfs/PartnershipProfiles2018.pdf">More information about Partnership profiles</a>.</p>
		</div>
</header>


	<div class="grid-x section">
		<table class="hover">
			<thead>
				<tr>
				{% for field in fields %}
					
					{% if field|slice:"-4:" != "link" %}
						<th>{{field|capfirst}}</th>
					{% endif %}
				{% endfor %}
				</tr>
			</thead>
			<tbody>


				{% for res in section %}
				<tr>
				
				{% if model_name == "Sector_Partnerships" %}
					<th>{{res.partnership_title}}</th>    
				    <td>{{res.target_industry}}</td>			
				    <td><a href='{{res.organization_link}}' target='_blank'>{{res.lead_applicant_organization}}</a></td>
					<td>{{res.contact_name}}</td>   		

					{% if res.plan_link|length < 3 %}
						<td>{{res.comprehensive_plan}}</td>
					{% else %}
						<td><a href='{{res.plan_link}}' target='_blank'>{{res.comprehensive_plan}}</a></td>
					{% endif %}
				
						
				{% elif model_name == "Employers_Served" %}
					<th>{{res.employer}}</th>    
				    
				    {% if res.new_hire_training != '' %}
						<td><img src="{% static 'web/images/yes.png' %}" width="15" /></td>
				    {% else %}
				    	<td></td>
				    {% endif %}

				    {% if res.incumbent_worker_training != '' %}
						<td><img src="{% static 'web/images/yes.png' %}" width="15" /></td>
				    {% else %}
				    	<td></td>
				    {% endif %}
					
				    <td>{{res.partnerships}}</td>	

				{% elif model_name == "Industry_Sectors" %}
					<th>{{res.partnership}}</th>					

				{% elif model_name == "New_Hire_Training_Activities" %}
					<th>{{res.partnership}}</th>
					<td>{{res.description_of_training_activities}}</td>	

				{% elif model_name == "Incumbent_Worker_Training_Activities" %}
					<th>{{res.partnership}}</th>	
					<td>{{res.description_of_training_activities}}</td>

				{% elif model_name == "Pipeline_Development_Activities" %}
					<th>{{res.partnership}}</th>	

				{% elif model_name == "New_Hires_Placed" %}
					<th>{{res.partnership}}</th>	
					<td>{{res.new_hires_placed}}</td>

				{% elif model_name == "Incumbent_Workers_Upskilled" %}
					<th>{{res.partnership}}</th>	
					<td>{{res.incumbent_workers_upskilled}}</td>

				{% elif model_name == "College_Internships_Completed" %}
					<th>{{res.partnership}}</th>	
					<td>{{res.activity_description}}</td>
					<td>{{res.college_internships_completed}}</td>

				{% elif model_name == "New_Career_Technial_High_School_Programs" %}
					<th>{{res.partnership}}</th>	
					<td>{{res.CTE_progam_description}}</td>

				{% elif model_name == "High_School_Students_Completing_Internships" %}
					<th>{{res.partnership}}</th>	
					<td>{{res.activity_description}}</td>
					<td>{{res.high_school_internships_completed}}</td>

				{% endif %}

				</tr>
				{% endfor %}
		

			</tbody>
		</table>


	</div>


	<footer>
		<div class="data-info"><a href="#performance">Data and Performance</a>, <a href="#overview">Overview</a>, <a href="#finances">Finances</a>, <a href="#demographics">Demographics</a> data as of 10/31/2017.</div>
		<div class="by">
			<a href="https://datasparkri.org"><img src="{% static 'web/images/dataspark-logo.png' %}" width="107" height="50" alt="Dataspark"></a>
			<a href="https://www.uri.edu"><img src="{% static 'web/images/the-university-or-rhode-island-logo.png' %}" width="126" height="50" alt="The University of Rhode Island"></a>
		</div>
	</footer>

	<!-- Compressed JavaScript -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/js/foundation.min.js"></script>

	<script src="https://code.highcharts.com/highcharts.js"></script>
	<script src="https://code.highcharts.com/modules/exporting.js"></script>

	<script src="{% static 'web/js/script.min.js' %}"></script>
	

	<script>
		$(document).foundation();
	</script>
</body>
</html>

web/templates/web/upload.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Dashboard</title>

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css" />

	<link rel="stylesheet" href="{% static "web/style.css" %}"/>
	
</head>
<body>
	<header>
		<div class="bg">
			<h1><a href="{% url 'web:index' %}">Real Jobs <span>Rhode Island</span></a></h1>
		</div>
	</header>
	
	<div class="grid-x section">
		

		<form action="{% url "web:upload_csv" %}" method="POST" enctype="multipart/form-data" class="form-horizontal"> 
			{% csrf_token %}
			<div class="form-group">
			    <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label">File: </label>
			    <div class="col-md-8">
			        <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
			    </div>                    
			</div>
			<div class="form-group">                    
			    <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
			         <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
			    </div> 
			</div>
			</form>
	</div>		


	<footer>
		<div class="data-info"><a href="#performance">Data and Performance</a>, <a href="#overview">Overview</a>, <a href="#finances">Finances</a>, <a href="#demographics">Demographics</a> data as of 10/31/2017.</div>
		<div class="by">
			<a href="https://datasparkri.org"><img src="{% static "web/images/dataspark-logo.png" %}" width="107" height="50" alt="Dataspark"></a>
			<a href="https://www.uri.edu"><img src="{% static "web/images/the-university-or-rhode-island-logo.png" %}" width="126" height="50" alt="The University of Rhode Island"></a>
		</div>
	</footer>

	<!-- Compressed JavaScript -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/js/foundation.min.js"></script>

	<script src="https://code.highcharts.com/highcharts.js"></script>
	<script src="https://code.highcharts.com/modules/exporting.js"></script>

	<script src="{% static "web/js/script.min.js" %}"></script>
	

	<script>
		$(document).foundation();
	</script>
</body>
</html>

web/templates/web/upload_csv.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Dashboard</title>

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css" />

	<link rel="stylesheet" href="{% static "web/style.css" %}"/>
	
</head>
<body>
	<header>
		<div class="bg">
			<h1><a href="{% url 'web:index' %}">Real Jobs <span>Rhode Island</span></a></h1>
		</div>
	</header>
	
	{{debug}}

	<div class="grid-x section">
		

		<form action="{% url "web:upload_csv" %}" method="POST" enctype="multipart/form-data" class="form-horizontal"> 
			{% csrf_token %}
		    
		    <h4><font color='red'><strong>!!!</strong></font> Uploading a new file <font color='red'> (.xlsx) </font> will override existing data</h4>
		    
		    <hr>
		    <select name="section" id="section">
				<option value="Sector_Partnerships"> 1. Sector Partnerships </option>
				<option value="Employers_Served"> 2. Employers Served </option>
				<option value="Industry_Sectors"> 3. Industry Sectors </option>
				<option value="New_Hire_Training_Activities"> 4. New Hire Training Activities </option>
				<option value="Incumbent_Worker_Training_Activities"> 5. Incumbent Worker Training Programs </option>
				<option value="Pipeline_Development_Activities"> 6. Pipeline Development Activities </option>
				<option value="New_Hires_Placed"> 7. New Hires Placed </option>
				<option value="Incumbent_Workers_Upskilled"> 8. Incumbent Workders Upskilled </option>
				<option value="College_Internships_Completed"> 9. College Internships Completed </option>
				<option value="New_Career_Technial_High_School_Programs"> 10. New Career & Technical High School Programms </option>
				<option value="High_School_Students_Completing_Internships"> 11. High School Students Completing Internships </option>
				<option value="Performance_Finances"> Performance and Finances </option>
Performance_Finances

		    </select><br/><br/>

		    <input type="file" name="csv_file" id="csv_file" class="form-control">
			<br/><br/>					    
		    <!-- <button class="btn btn-primary"> Upload </button>  -->
		   	<input type="submit" value=" Download " name="download"> &nbsp; &nbsp; 
			<input type="submit" value="  Upload  " name="submit"><br/> <p><h4>{{message|safe}}</h4></p>

			<br/><br/>
			<h3>File Templates </h3>
			<hr>

			<table>
				<tr>
					<td><a href="../../static/web/files/xlsx/1. Sector Partnerships.xlsx">Sector Partnerships</a></td>
					<td><a href="../../static/web/files/xlsx/2. Employers Served.xlsx">Employers Served</a></td>
					<td><a href="../../static/web/files/xlsx/3. Industry Sectors.xlsx">Industry Sectors</a></td>
				</tr>
				<tr>
					<td><a href="../../static/web/files/xlsx/4. New Hire Training Activities.xlsx">New Hire Training Activities</a></td>
					<td><a href="../../static/web/files/xlsx/5. Incumbent Worker Training Activities.xlsx">Incumbent Worker Training Activities</a></td>
					<td><a href="../../static/web/files/xlsx/6. Pipeline Development Activities.xlsx">Pipeline Development Activities</a></td>
				</tr>
				<tr>
					<td><a href="../../static/web/files/xlsx/7. New Hires Placed.xlsx">New Hires Placed</a></td>
					<td><a href="../../static/web/files/xlsx/8. Incumbent Worker Upskilled.xlsx">Incumbent Worker Upskilled</a></td>
					<td><a href="../../static/web/files/xlsx/9. College Internships Completed.xlsx">College Internships Completed</a></td>
				</tr>
				<tr>
					<td><a href="../../static/web/files/xlsx/10. New Career and Technical High School Programs.xlsx">New Career and Technical High School Programs</a></td>
					<td><a href="../../static/web/files/xlsx/11. High School Students Completing Internships.xlsx">High School Students Completing Internships</a></td>
					<td><a href="../../static/web/files/xlsx/Performance and Finances.xlsx">Performance and Finances</a></td>
				</tr>
			</table>
			</form>
	</div>		


	<footer>
		<div class="data-info"><a href="#performance">Data and Performance</a>, <a href="#overview">Overview</a>, <a href="#finances">Finances</a>, <a href="#demographics">Demographics</a> data as of 10/31/2017.</div>
		<div class="by">
			<a href="https://datasparkri.org"><img src="{% static 'web/images/dataspark-logo.png' %}" width="107" height="50" alt="Dataspark"></a>
			<a href="https://www.uri.edu"><img src="{% static 'web/images/the-university-or-rhode-island-logo.png' %}" width="126" height="50" alt="The University of Rhode Island"></a>
		</div>
	</footer>

	<!-- Compressed JavaScript -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/js/foundation.min.js"></script>

	<script src="https://code.highcharts.com/highcharts.js"></script>
	<script src="https://code.highcharts.com/modules/exporting.js"></script>

	<script src="{% static "web/js/script.min.js" %}"></script>
	

	<script>
		$(document).foundation();
	</script>
</body>
</html>